
import { injectable } from '@theia/core/shared/inversify';
import * as fs from 'fs';
import * as path from 'path';
import { URI } from '@theia/core';
import {
    AICodegenService,
    CodegenRequest,
    CodegenPlan,
    GeneratedPatch,
    ApplyPatchResult
} from '../../../local-brain/src/common/protocol';
// We do not inject LocalBrainChatService because it's technically in the other package and not exposed directly here,
// for the vertical slice we use the deterministic mock inside generatePatch.

@injectable()
export class AICodegenServiceImpl implements AICodegenService {

    private plans = new Map<string, CodegenPlan>();
    private patches = new Map<string, GeneratedPatch>();

    private updateProjectState(workspaceRoot: string, task: string, risk?: string) {
        const p = path.join(workspaceRoot, '.localforge', 'project-state.json');
        try {
            if (!fs.existsSync(path.dirname(p))) fs.mkdirSync(path.dirname(p), { recursive: true });
            let state: any = { phase: 'mvp-build', knownRisks: [], nextRecommendedAction: '' };
            if (fs.existsSync(p)) {
                state = JSON.parse(fs.readFileSync(p, 'utf8'));
            }

            state.lastCompletedTask = task;
            if (risk) state.knownRisks.push(risk);

            fs.writeFileSync(p, JSON.stringify(state, null, 2), 'utf8');
        } catch (e) {
            console.error("Failed to update project-state.json", e);
        }
    }

    public async createEditPlan(input: CodegenRequest): Promise<CodegenPlan> {
        const id = `plan_${Date.now()}`;
        const rootUri = new URI(input.workspacePath);
        const rootPath = rootUri.path.toString();

        // 1. Gather Context
        const contextGathered: string[] = [];

        const bpPath = path.join(rootPath, 'docs', 'app-blueprint.md');
        if (fs.existsSync(bpPath)) contextGathered.push('/docs/app-blueprint.md');

        const pkgPath = path.join(rootPath, input.appPath, 'package.json');
        if (fs.existsSync(pkgPath)) contextGathered.push(`${input.appPath}/package.json`);

        const statePath = path.join(rootPath, '.localforge', 'project-state.json');
        if (fs.existsSync(statePath)) contextGathered.push('.localforge/project-state.json');

        const plan: CodegenPlan = {
            id,
            request: input,
            contextGathered,
            status: 'ready'
        };

        this.plans.set(id, plan);
        return plan;
    }

    public async generatePatch(planId: string): Promise<GeneratedPatch> {
        const plan = this.plans.get(planId);
        if (!plan) throw new Error('Plan not found');

        const patchId = `patch_${Date.now()}`;
        let patch: GeneratedPatch;

        const promptLower = plan.request.userPrompt.toLowerCase();

        if (promptLower.includes('dark mode') || promptLower.includes('theme')) {
            patch = {
                id: patchId,
                summary: 'Add dark mode toggle component',
                files: [
                    {
                        path: `${plan.request.appPath}/src/components/ThemeToggle.tsx`,
                        action: 'create',
                        after: `export function ThemeToggle() {\n  return (\n    <button className="p-2 border rounded bg-gray-200 dark:bg-gray-800">\n      Toggle Theme\n    </button>\n  );\n}`
                    },
                    {
                        path: `${plan.request.appPath}/src/app/page.tsx`,
                        action: 'modify',
                        before: `export default function Home() {\n  return (\n    <main className="p-8">\n      <h1 className="text-2xl font-bold">/ (Landing Page)</h1>\n      <p className="mt-4">Placeholder generated by LocalForge Blueprint.</p>\n    </main>\n  );\n}`,
                        after: `import { ThemeToggle } from '../components/ThemeToggle';\n\nexport default function Home() {\n  return (\n    <main className="p-8">\n      <div className="flex justify-between items-center mb-8">\n        <h1 className="text-2xl font-bold">/ (Landing Page)</h1>\n        <ThemeToggle />\n      </div>\n      <p className="mt-4">Placeholder generated by LocalForge Blueprint.</p>\n    </main>\n  );\n}`
                    }
                ],
                commands: [
                    { command: 'pnpm install next-themes', reason: 'Provides robust theme management hooks.', requiresApproval: true }
                ],
                risks: ['Adds client-side state', 'May need theme persistence logic verified']
            };
        } else {
            // Generic fallback patch
            patch = {
                id: patchId,
                summary: `Implement: ${plan.request.userPrompt}`,
                files: [
                    {
                        path: `${plan.request.appPath}/src/components/NewFeature.tsx`,
                        action: 'create',
                        after: `export function NewFeature() {\n  return <div>New Feature Generated by AI</div>;\n}`
                    }
                ],
                risks: ['Untested client component generation']
            };
        }

        this.patches.set(patchId, patch);
        return patch;
    }

    public async applyPatch(patchId: string): Promise<ApplyPatchResult> {
        const patch = this.patches.get(patchId);
        if (!patch) throw new Error('Patch not found');

        const rootPath = new URI(process.cwd()).path.toString();

        let filesModified = 0;

        try {
            for (const file of patch.files) {
                const fullPath = path.join(rootPath, file.path);

                if (file.action === 'create' || file.action === 'modify') {
                    if (!file.after) throw new Error(`Missing 'after' content for file ${file.path}`);

                    if (!fs.existsSync(path.dirname(fullPath))) {
                        fs.mkdirSync(path.dirname(fullPath), { recursive: true });
                    }

                    fs.writeFileSync(fullPath, file.after, 'utf8');
                    filesModified++;
                } else if (file.action === 'delete') {
                    if (fs.existsSync(fullPath)) {
                        fs.unlinkSync(fullPath);
                        filesModified++;
                    }
                }
            }

            this.updateProjectState(rootPath, patch.summary, patch.risks[0]);

            this.patches.delete(patchId);
            return { success: true, filesModified };
        } catch (e) {
            return { success: false, filesModified, error: String(e) };
        }
    }

    public async getActivePatch(): Promise<GeneratedPatch | null> {
        // Return the first active patch for the UI
        if (this.patches.size === 0) return null;
        return this.patches.values().next().value;
    }

    public async rejectPatch(patchId: string): Promise<void> {
        const patch = this.patches.get(patchId);
        if (patch) {
            const rootPath = new URI(process.cwd()).path.toString();
            this.updateProjectState(rootPath, `Rejected proposed patch: ${patch.summary}`);
            this.patches.delete(patchId);
        }
    }
}
