import { AIProviderAdapter } from './base-provider';
import { LocalBrainChatRequest, AIModel, ProviderConnectionStatus, AIProviderInfo } from '../../common/protocol';

export class MockProvider implements AIProviderAdapter {
    getInfo(): AIProviderInfo {
        return {
            id: 'mock-provider',
            displayName: 'Mock Provider (Offline)',
            type: 'mock',
            supportsStreaming: false
        };
    }

    async listModels(): Promise<AIModel[]> {
        return [{ id: 'mock-model', displayName: 'Mock Model', contextWindow: 4096 }];
    }

    async validateConnection(): Promise<ProviderConnectionStatus> {
        return { connected: true };
    }

    async chat(request: LocalBrainChatRequest): Promise<string> {
        const promptLower = request.messages[request.messages.length - 1].content.toLowerCase();

        if (promptLower.includes('dark mode') || promptLower.includes('theme')) {
            return `\`\`\`json
{
  "summary": "Add dark mode toggle component",
  "files": [
    {
      "path": "apps/web/src/components/ThemeToggle.tsx",
      "action": "create",
      "after": "export function ThemeToggle() {\\n  return (\\n    <button className=\\"p-2 border rounded bg-gray-200 dark:bg-gray-800\\">\\n      Toggle Theme\\n    </button>\\n  );\\n}"
    },
    {
      "path": "apps/web/src/app/page.tsx",
      "action": "modify",
      "before": "export default function Home() {\\n  return (\\n    <main className=\\"p-8\\">\\n      <h1 className=\\"text-2xl font-bold\\">/ (Landing Page)</h1>\\n      <p className=\\"mt-4\\">Placeholder generated by LocalForge Blueprint.</p>\\n    </main>\\n  );\\n}",
      "after": "import { ThemeToggle } from '../components/ThemeToggle';\\n\\nexport default function Home() {\\n  return (\\n    <main className=\\"p-8\\">\\n      <div className=\\"flex justify-between items-center mb-8\\">\\n        <h1 className=\\"text-2xl font-bold\\">/ (Landing Page)</h1>\\n        <ThemeToggle />\\n      </div>\\n      <p className=\\"mt-4\\">Placeholder generated by LocalForge Blueprint.</p>\\n    </main>\\n  );\\n}"
    }
  ],
  "commands": [
    { "command": "pnpm install next-themes", "reason": "Provides robust theme management hooks.", "requiresApproval": true }
  ],
  "risks": ["Adds client-side state", "May need theme persistence logic verified"]
}
\`\`\``;
        }

        return `\`\`\`json
{
  "summary": "Implement: ${promptLower.substring(0, 20)}...",
  "files": [
    {
      "path": "apps/web/src/components/NewFeature.tsx",
      "action": "create",
      "after": "export function NewFeature() {\\n  return <div>New Feature Generated by AI</div>;\\n}"
    }
  ],
  "risks": ["Untested client component generation"]
}
\`\`\``;
    }
}
